### ISSUE TITLE
리뷰 피드백

### ISSUE THREAD

**Issue by withlhw** [mixed/webworker-sample#1]
전체적으로 심플하게 luminosityGrey 예제를 구현하는것이 좋을것 같습니다.

1. luminosityGrey 알고리즘이 복잡해서 한 눈에 와 닫지 않는것 같습니다.
개인적으로는 아래와 같이 RGB의 weight를 주지 않는 방식으로 처리하는것 심플할것 같아요.
Gray = (Red + Green + Blue) / 3

2.  Canvas + png 이미지
Canvas와 png 이미지 방식으로 예제를 구성하다 보니 다소 복잡해 진것 같아요.

Canvas와 외부 png 이미지를 사용하지 않고, 아래와 같이 rgb 값을 직접 이용하거나, data URI (data:image/jpg) 형태로 사용하는 등 좀 심플하게 만들 수 있는지 고민해 봐야 할것 같습니다.
```
var map = [
 [0, 0, 0, 0, 0, 0, 0],
 [1, 1, 0, 1, 0, 1, 1],
 [0, 1, 0, 1, 0, 0, 0],
 [0, 1, 0, 1, 0, 1, 1],
 [0, 0, 0, 1, 0, 0, 0],
 [1, 0, 0, 1, 1, 1, 1],
 [1, 1, 0, 1, 1, 0, 1],
];
```

3. html은 https://w3c.github.io/workers/에 있는 예제들 처럼 간단하게 구현하는게 심플할것 같습니다.
```
<html>
 <head>
  <title>Workers example: Multiviewer viewer</title>
```

4. import.js와 worker.js를 합쳐서 worker.js 하나로 만들면 간단할 것 같아요.

**Comment by mixed** [comment]
@withlhw 
매우 좋네요!! 반영 후에 알려드릴께요~

**Comment by mixed** [comment]
@withlhw 
형욱님. 아래와 같이 수정했는데요. 다시 한번 확인 부탁드려요.
1. DONE.
2. data-uri로 변경했는데요. 이미지여야 좀 좋아보이는데 그냥 간단히 픽셀 변환만 하는게 좋으신가요?
3. 좀 심플하게 했어요.
4. DONE

**Comment by withlhw** [comment]
- 3번 관련으로 아래 처럼 좀 더 심플하게 head tag는 title만 추가하고, CSS도 사용하지 않고 구성하면 더 좋을것 같아요.

```
<!DOCTYPE HTML>
<html>
 <head>
  <title>Worker example: Multicore computation</title>
 </head>
 <body>
  <p>Result: <output id="result"></output></p>
  <script>
   var worker = new Worker('worker.js');
   worker.onmessage = function (event) {
     document.getElementById('result').textContent = event.data;
   };
  </script>
 </body>
</html>
```
- 2번은 외부 이미지도 상관은 없는데 Canvas 코드가 좀 많아서 Canvas 말고 이미지 데이터에 직접 luminosityGrey 효과를 적용할 수는 없을까요?
- 마지막으로 코딩 스타일도 맞추면 더 보기 좋을것 같아요.

**Comment by mixed** [comment]
@withlhw 
-  넵. 다시 정리했습니다
- 저도 좀 찾아봤는데 ImageData를 직접 넣는 방법이 없더라구요. 아니면 직접 그려야 하는데 그건 더 길구요. 그래서 다시 image을 넣었습니다.
- 정리했습니다.
